name: Build Pro APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
      - name: Fix Gradle & Build Pro
        run: |
          rm -rf android
          rm -rf pubspec.lock
          flutter create . --platforms=android --project-name railsathi_pro
          flutter pub get
          flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: railsathi-pro-apk
          path: build/app/outputs/flutter-apk/app-release.apk
